### ISSUE TITLE
Unsound atomic borrowing

### ISSUE THREAD

**Issue by zakarumych** [azriel91/rt_ref#1]
This crate implements atomic borrowing but implementation is unsound.
For example `CellRef` rampant cloning can overflow counter back to `0`

**Comment by azriel91** [comment]
It technically is unsound, though probably very unusual to get 4 billion / 9 quintillion references to something in memory :sweat_smile:.

Nevertheless I think it can work with a `try_clone()` that compares the returned value with `usize::MAX`.

Or perhaps practically, panicking if it reaches that high.

**Comment by zakarumych** [comment]
It would be OK if there were requirement to hold them all in memory.
After all, it's hard to hold `usize::MAX + 1` objects in memory, they simply won't fit.

That's why, for instance, it is somewhat safe to assume that there won't be `usize::MAX` or even `isize::MAX` threads that access atomic variable concurrently.

But it's easy to do `std::mem::forget(CellRef::clone(&r))` and overflow the counter.

**Comment by zakarumych** [comment]
Typical solution is to panic, explaining that degenerate programs which do clone-forget in loop are not supported.

**Comment by azriel91** [comment]
Cool thanks, I've implemented that in #2; though missed the docs part -- shall update that in `main` before releasing.
